### ISSUE TITLE
Font for tab titles is too large

### ISSUE THREAD

**Issue by special** [CrimsonAS/gtkplatform#29]
The font used on tab titles, groupbox headers, and a few other things is too large under the GTK plugin, compared to XCB. I've seen this in widgets and qtquickcontrols applications, and I've only tried on a high DPI screen. In some cases it will end up actually clipping off of the widget.

GTK:
![zeal-gtk](https://user-images.githubusercontent.com/80188/31104029-4b614958-a78f-11e7-9855-55fe10a6a468.png)
XCB:
![zeal-xcb](https://user-images.githubusercontent.com/80188/31104033-509b9130-a78f-11e7-81aa-11c305686663.png)

**Comment by rburchell** [comment]
It's a bit of a mystery so far, the font is bolded, but that seems to be the only really noteworthy thing that happens (no setPointSize/setPixelSize). I'm not sure what would be causing this.

**Comment by rburchell** [comment]
[this is a mass update]

This is polite notice that gtkplatform is effectively end of life. Due to this, I've decided to archive the project.

I (and I think, the other contributors) have not been using it in quite some time, and I don't see that situation changing any time soon. In addition, none of us really have the time that it takes to do what it takes to keep the lights on, and this situation is going to get a lot harder soon with the impending arrival of Qt 6 and gtk 4 on the horizon.

Should anyone wish to take it over, you have my blessing to do so :)
