### ISSUE TITLE
Consider implementing status icons via KStatusNotifierItems

### ISSUE THREAD

**Issue by jhasse** [CrimsonAS/gtkplatform#32]
The Wayland backend (`QT_QPA_PLATFORM=wayland`) supports tray icons via KStatusNotifierItems, which will integrate nicely into GNOME Shell via this extension: https://github.com/ubuntu/gnome-shell-extension-appindicator

This would be a great addition for some Qt apps and maybe the code can be copied from the Wayland backend (should just be DBus calls).

**Comment by rburchell** [comment]
I'm not totally convinced (because of the upstream stance of not wanting tray icons), but I'll think about it.

**Comment by davidedmundson** [comment]
You shouldnt need to write any code for this.

It's built into Qt as long as the QPT isn't doing it's only system trays.

**Comment by rburchell** [comment]
There is, in order to provide some level of notification support. Right now through libnotify, but I'll also be wiring up GNotification for GtkApplication-using things in the future. At least that is the plan: I've had limited time to work on that lately.

**Comment by rburchell** [comment]
[this is a mass update]

This is polite notice that gtkplatform is effectively end of life. Due to this, I've decided to archive the project.

I (and I think, the other contributors) have not been using it in quite some time, and I don't see that situation changing any time soon. In addition, none of us really have the time that it takes to do what it takes to keep the lights on, and this situation is going to get a lot harder soon with the impending arrival of Qt 6 and gtk 4 on the horizon.

Should anyone wish to take it over, you have my blessing to do so :)
