### ISSUE TITLE
PPSSPP is screwed up

### ISSUE THREAD

**Issue by myfreeweb** [CrimsonAS/gtkplatform#34]
The PPSSPP UI looks amazing :D The menu is in a separate window, not in the right place, and there's an extra empty window:

![ppsspp-gtk](https://user-images.githubusercontent.com/208340/34158173-70ef833c-e4d5-11e7-941b-0aabfb6d5b9b.png)

But at least it's not semi-transparent like `wayland-egl` is for some reason:

![ppsspp-wegl](https://user-images.githubusercontent.com/208340/34158297-d48fc76c-e4d5-11e7-9f9d-6597c7e96162.png)

(FreeBSD 12-CURRENT, Weston, GTK 3.22.26, Qt 5.7.1, gtkplatform 0.2.1, PPSSPP-qt5 1.5.4.)

**Comment by rburchell** [comment]
If I had to guess, I would think that there might be some window embedding going on there which is not really supported right now (QPlatformWindow::setParent etc), see also #22.

**Comment by myfreeweb** [comment]
Oh, sorry, didn't notice that issue. Yeah, definitely embedding for the main content. Not sure about the empty window…

**Comment by rburchell** [comment]
No problem, let's keep this open for investigation. I don't know when/if I will have any time to look at this in the near future, so if you have time to do some digging, that would be appreciated.

**Comment by rburchell** [comment]
[this is a mass update]

This is polite notice that gtkplatform is effectively end of life. Due to this, I've decided to archive the project.

I (and I think, the other contributors) have not been using it in quite some time, and I don't see that situation changing any time soon. In addition, none of us really have the time that it takes to do what it takes to keep the lights on, and this situation is going to get a lot harder soon with the impending arrival of Qt 6 and gtk 4 on the horizon.

Should anyone wish to take it over, you have my blessing to do so :)
