### ISSUE TITLE
Some windows have wrong HiDPI scaling initially (until resize)

### ISSUE THREAD

**Issue by myfreeweb** [CrimsonAS/gtkplatform#40]
This started happening with Qt 5.9, I think it was fine in 5.7:

![wayland-screenshot-2018-05-09_14-19-01-fs8](https://user-images.githubusercontent.com/208340/39812157-3cd66452-5394-11e8-8c4a-513bf85a7387.png)

The contents aren't rendered at the correct scale until I start resizing the window.

Sometimes it happens to the main application window, sometimes it doesn't (like with Picard here), but it always happens with additional windows, context menus, etc. This is especially bad for context menus.

**Comment by rburchell** [comment]
Can you point to an application and give steps to reproduce this? I haven't noticed any issues with 5.9 to date:

gtk3-3.22.30-1.fc28.x86_64
qt5-qtbase-5.10.1-6.fc28.x86_64

**Comment by myfreeweb** [comment]
That's 5.10 not 5.9 :)

I have gtk 3.22.29, Qt 5.9.4, and Weston master. This is happening in *all* applications, even just `qt5ct`.

**Comment by rburchell** [comment]
Sorry, I forgot I upgraded. Previously I was on f27, which does contain 5.9, and had no issues.

Unfortunately, as I can't reproduce this, I won't be able to fix it. If you can identify the problem, I might be able to help guide you towards a fix. I'd suggest looking in QGtkScreen as being a good starting point, though another likely possibility would be an expose event sent at the wrong time (in QGtkWindow).

**Comment by libcg** [comment]
@rburchell Please don't close issues that are not fixed even if you can't reproduce them. It's likely that it will discourage some people from reporting bugs if you keep doing that. Thanks.

**Comment by rburchell** [comment]
First up, thanks for the feedback. Let me explain the way I tend to work with trackers.

Issues are used as things I can act on when I have time to do so. It doesn't give me any value to have issues open that I can't do anything about because I can't reproduce them. I don't see how it adds any value to the reporter(s) either, to have a bug left open indefinitely without action, as is often the case in other open source projects.

So to state it clearly: I close things because I am being honest in saying that I won't be spending time on this, not because I'm dismissing the possibility of a problem _somewhere_. There certainly might be one, but as I can't see that problem, I can't offer a fix.

I'm happy to help try offer suggestions for where to look for a solution (as I did in my initial answer above), but until there's a concrete suggestion for what the problem is that I can look at, I am not able to do anything more with this.

If I get new information on what the problem is, if I can reproduce it myself, or if someone pops up with a fix - that's of course great, and then there's always the potential to reopen things, it's not like it's a permanent death sentence for the issue.

It's just me being honest about my priorities, so that reporter(s) get quicker feedback than waiting months, or years, to realize the same outcome of nothing happening, and in the meantime, I'm left with a list of issues that I can actually do things with, rather than being left with an ever-expanding list of things that I have no idea whether or not are still a problem.

**Comment by libcg** [comment]
If you can't offer a fix maybe someone else will, but the issues need to be visible in the first place. It doesn't help in any way to close them.
