### ISSUE TITLE
QFileDialog configured as directory picker shows up as file save picker

### ISSUE THREAD

**Issue by myfreeweb** [CrimsonAS/gtkplatform#41]
The [Android File Transfer app](https://github.com/whoozle/android-file-transfer-linux) uses a directory picker for downloading files (I think it's [this code](https://github.com/whoozle/android-file-transfer-linux/blob/53230d606e44b7901e931a347b7f59ed3a963e2a/qt/mainwindow.cpp#L410-L412).)

It's supposed to look like:

![wayland-screenshot-2018-05-18_13-10-36-fs8](https://user-images.githubusercontent.com/208340/40230458-3846081c-5aa0-11e8-9cee-605c9ed2b8ce.png)

But with GTK, it looks like a save file dialog, it requires a name:

![wayland-screenshot-2018-05-18_13-18-18-fs8](https://user-images.githubusercontent.com/208340/40230480-48b0ec9e-5aa0-11e8-96a7-98f5ab59dedc.png)

**Comment by rburchell** [comment]
Well, the problem seems to be more that they are asking for a save dialog (setAcceptMode(QFileDialog::AcceptSave)), but they optionally want a filename, or a directory name. So really, I would expect that to be two separate actions with two separate dialogs: a directory picker (set default save path), plus a save-file-as dialog. That the "built in" dialog in Qt sort of allows this to work does not mean that every native platform will.

Can you point to any native applications with behaviour similar to this to examine? I haven't been able to find any with a quick look around.

That having been said, I think we might be able to make this work by looking at using GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER on gtkFileChooserAction() rather than forcing GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER, but then I guess we'd trade one bug for another, in that you'd never be able to create a new folder... Tricky...

**Comment by rburchell** [comment]
[this is a mass update]

This is polite notice that gtkplatform is effectively end of life. Due to this, I've decided to archive the project.

I (and I think, the other contributors) have not been using it in quite some time, and I don't see that situation changing any time soon. In addition, none of us really have the time that it takes to do what it takes to keep the lights on, and this situation is going to get a lot harder soon with the impending arrival of Qt 6 and gtk 4 on the horizon.

Should anyone wish to take it over, you have my blessing to do so :)
