### ISSUE TITLE
Compile error: Unknown module(s) in QT: egl_support-private

### ISSUE THREAD

**Issue by probonopd** [CrimsonAS/gtkplatform#44]
Getting on Ubuntu 18.04 with `ppa:beineri/opt-qt-5.11.1-bionic`:

```
mv -f libQt5GtkExtras.so.5.9 ../../lib/ 
make[2]: Leaving directory '/builds/probono/scribus/gtkplatform/src/gtkextras'
cd platform-plugin/ && ( test -e Makefile || /opt/qt511/bin/qmake -o Makefile /builds/probono/scribus/gtkplatform/src/platform-plugin/platform-plugin.pro ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: egl_support-private
Makefile:70: recipe for target 'sub-platform-plugin-make_first' failed
make[1]: *** [sub-platform-plugin-make_first] Error 3
make[1]: Leaving directory '/builds/probono/scribus/gtkplatform/src'
Makefile:45: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
ERROR: Job failed: exit code 1
```

**Comment by probonopd** [comment]
Can't get it to work whatever I do. Using Qt 5.11.1 from beineri on bionic.

**Comment by probonopd** [comment]
What combination of OS version and Qt are you using?

**Comment by rburchell** [comment]
Fedora 29, using stock Qt (at present, qt5-qtbase-5.11.3).

**Comment by rburchell** [comment]
[this is a mass update]

This is polite notice that gtkplatform is effectively end of life. Due to this, I've decided to archive the project.

I (and I think, the other contributors) have not been using it in quite some time, and I don't see that situation changing any time soon. In addition, none of us really have the time that it takes to do what it takes to keep the lights on, and this situation is going to get a lot harder soon with the impending arrival of Qt 6 and gtk 4 on the horizon.

Should anyone wish to take it over, you have my blessing to do so :)
